env:
  - DOCKER_COMPOSE_VERSION=1.4.2

services: docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker -v
  - cp example.env .env
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  - npm run build

script:
  - npm test