version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
  metascore:
    container_name: app
    restart: always
    build: .
    ports:
      - "4444:4444"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017