version: "3"
services:
  backend-test:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.test 
      args:
        port: ${PORT}
    env_file:
      - ../.env
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      WAIT_HOSTS: database:27017
  database:
    image: mongo:latest
    env_file:
      - ../.env
    volumes:
      - ".${MONGO_TEST_DATA_DIR}:${MONGO_TEST_DATA_DIR}"
    expose:
      - 27017
    command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"
#  mongo-seed:
#    build:
#      context: ../
#      dockerfile: docker/Dockerfile.seed
#    links:
#      - database